/*
 * Created on 21 oct. 2014 ( Time 13:09:05 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package main.java.org.demo.bean.jpa;
import java.io.Serializable;

import javax.persistence.*;

/**
 * Composite primary key for entity "ParticipationsEntity" ( stored in table "PARTICIPATIONS" )
 *
 * @author Telosys Tools Generator
 *
 */
 @Embeddable
public class ParticipationsEntityKey implements Serializable {
    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY KEY ATTRIBUTES 
    //----------------------------------------------------------------------
    @Column(name="ID", nullable=false)
    private Integer    id           ;
    
    @Column(name="EMAIL", nullable=false, length=255)
    private String     email        ;
    

    //----------------------------------------------------------------------
    // CONSTRUCTORS
    //----------------------------------------------------------------------
    public ParticipationsEntityKey() {
        super();
    }

    public ParticipationsEntityKey( Integer id, String email ) {
        super();
        this.id = id ;
        this.email = email ;
    }
    
    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR KEY FIELDS
    //----------------------------------------------------------------------
    public void setId( Integer value ) {
        this.id = value;
    }
    public Integer getId() {
        return this.id;
    }

    public void setEmail( String value ) {
        this.email = value;
    }
    public String getEmail() {
        return this.email;
    }


    //----------------------------------------------------------------------
    // equals METHOD
    //----------------------------------------------------------------------
	public boolean equals(Object obj) { 
		if ( this == obj ) return true ; 
		if ( obj == null ) return false ;
		if ( this.getClass() != obj.getClass() ) return false ; 
		ParticipationsEntityKey other = (ParticipationsEntityKey) obj; 
		//--- Attribute id
		if ( id == null ) { 
			if ( other.id != null ) 
				return false ; 
		} else if ( ! id.equals(other.id) ) 
			return false ; 
		//--- Attribute email
		if ( email == null ) { 
			if ( other.email != null ) 
				return false ; 
		} else if ( ! email.equals(other.email) ) 
			return false ; 
		return true; 
	} 


    //----------------------------------------------------------------------
    // hashCode METHOD
    //----------------------------------------------------------------------
	public int hashCode() { 
		final int prime = 31; 
		int result = 1; 
		
		//--- Attribute id
		result = prime * result + ((id == null) ? 0 : id.hashCode() ) ; 
		//--- Attribute email
		result = prime * result + ((email == null) ? 0 : email.hashCode() ) ; 
		
		return result; 
	} 


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() {
		StringBuffer sb = new StringBuffer(); 
		sb.append(id); 
		sb.append("|"); 
		sb.append(email); 
        return sb.toString();
    }
}
