
/*
 * Created on 30 oct. 2014 ( Time 13:59:50 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package main.java.org.demo.mock;

import java.util.LinkedList;
import java.util.List;

import main.java.org.demo.bean.jpa.OrganizersEntity;
import main.java.org.demo.mock.tool.MockValues;

public class OrganizersEntityMock {

	private MockValues mockValues = new MockValues();
	
	/**
	 * Creates an instance with random Primary Key
	 * @return
	 */
	public OrganizersEntity createInstance() {
		// Primary Key values

		return createInstance( mockValues.nextInteger() );
	}
	
	/**
	 * Creates an instance with a specific Primary Key
	 * @param id1
	 * @return
	 */
	public OrganizersEntity createInstance( Integer id ) {
		OrganizersEntity entity = new OrganizersEntity();
		// Init Primary Key fields
		entity.setId( id) ;
		// Init Data fields
		entity.setEmail( mockValues.nextString(255) ) ; // java.lang.String 
		entity.setPassword( mockValues.nextString(255) ) ; // java.lang.String 
		// Init Link fields (if any)
		// setListOfEvents( TODO ) ; // List<Events> 
		return entity ;
	}
	
	/**
	 * Creates a list of instances
	 * @param count number of instances to be created
	 * @return
	 */
	public List<OrganizersEntity> createList(int count) {
		List<OrganizersEntity> list = new LinkedList<OrganizersEntity>();		
		for ( int i = 1 ; i <= count ; i++ ) {
			list.add( createInstance() );
		}
		return list;
	}
}
