
/*
 * Created on 30 oct. 2014 ( Time 13:59:50 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package main.java.org.demo.mock;

import java.util.LinkedList;
import java.util.List;

import main.java.org.demo.bean.jpa.ParticipationsEntity;
import main.java.org.demo.mock.tool.MockValues;

public class ParticipationsEntityMock {

	private MockValues mockValues = new MockValues();
	
	/**
	 * Creates an instance with random Primary Key
	 * @return
	 */
	public ParticipationsEntity createInstance() {
		// Primary Key values

		return createInstance( mockValues.nextInteger() );
	}
	
	/**
	 * Creates an instance with a specific Primary Key
	 * @param id1
	 * @return
	 */
	public ParticipationsEntity createInstance( Integer id ) {
		ParticipationsEntity entity = new ParticipationsEntity();
		// Init Primary Key fields
		entity.setId( id) ;
		// Init Data fields
		entity.setEmail( mockValues.nextString(255) ) ; // java.lang.String 
		entity.setNom( mockValues.nextString(100) ) ; // java.lang.String 
		entity.setPrenom( mockValues.nextString(100) ) ; // java.lang.String 
		entity.setSociete( mockValues.nextString(255) ) ; // java.lang.String 
		// Init Link fields (if any)
		// setEvents( TODO ) ; // Events 
		return entity ;
	}
	
	/**
	 * Creates a list of instances
	 * @param count number of instances to be created
	 * @return
	 */
	public List<ParticipationsEntity> createList(int count) {
		List<ParticipationsEntity> list = new LinkedList<ParticipationsEntity>();		
		for ( int i = 1 ; i <= count ; i++ ) {
			list.add( createInstance() );
		}
		return list;
	}
}
