/*
 * Created on 30 oct. 2014 ( Time 13:59:50 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package test.java.org.demo.test.persistence;


import main.java.org.demo.bean.jpa.OrganizersEntity;
import main.java.org.demo.mock.OrganizersEntityMock;
import main.java.org.demo.persistence.PersistenceServiceProvider;
import main.java.org.demo.persistence.services.OrganizersPersistence;

import org.junit.Assert;
import org.junit.Test;

/**
 * JUnit test case for Organizers persistence service
 * 
 * @author Telosys Tools Generator
 *
 */
public class OrganizersPersistenceTest 
{
	@Test
	public void test1() {
		
		System.out.println("Test count ..." );
		
		OrganizersPersistence service = PersistenceServiceProvider.getService(OrganizersPersistence.class);
		System.out.println("CountAll = " + service.countAll() );
	}
	
	@Test
	public void test2() {
		
		System.out.println("Test Organizers persistence : delete + load ..." );
		
		OrganizersPersistence service = PersistenceServiceProvider.getService(OrganizersPersistence.class);
		
		OrganizersEntityMock mock = new OrganizersEntityMock();
		
		// TODO : set primary key values here 
		process( service, mock, 0  );
		// process( service, mock, ... );
	}

	private void process(OrganizersPersistence service, OrganizersEntityMock mock, Integer id ) {
		System.out.println("----- "  );
		System.out.println(" . load : " );
		OrganizersEntity entity = service.load( id );
		if ( entity != null ) {
			// Found 
			System.out.println("   FOUND : " + entity );
			
			// Save (update) with the same values to avoid database integrity errors  
			System.out.println(" . save : " + entity );
			service.save(entity);
			System.out.println("   saved : " + entity );
		}
		else {
			// Not found 
			System.out.println("   NOT FOUND" );
			// Create a new instance 
			entity = mock.createInstance( id ) ;
			Assert.assertNotNull(entity);

			// No reference : insert is possible 
			// Try to insert the new instance
			System.out.println(" . insert : " + entity );
			service.insert(entity);
			System.out.println("   inserted : " + entity );

			System.out.println(" . delete : " );
			boolean deleted = service.delete( id );
			System.out.println("   deleted = " + deleted);
			Assert.assertTrue(deleted) ;
		}		
	}
}
