/*
 * Created on 27 oct. 2014 ( Time 14:32:44 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */

package main.java.org.demo.persistence.services.jpa;


import javax.persistence.EntityManager;
import javax.persistence.PersistenceException;
import javax.persistence.Query;

import main.java.org.demo.bean.jpa.ParticipationsEntity;
import main.java.org.demo.bean.jpa.ParticipationsEntityKey;
import main.java.org.demo.persistence.commons.jpa.GenericJpaService;
import main.java.org.demo.persistence.commons.jpa.JpaOperation;
import main.java.org.demo.persistence.services.ParticipationsPersistence;

/**
 * JPA implementation for basic persistence operations ( entity "Participations" )
 * 
 * @author Telosys Tools Generator
 *
 */
public class ParticipationsPersistenceJPA extends GenericJpaService<ParticipationsEntity, ParticipationsEntityKey> implements ParticipationsPersistence {

	/**
	 * Constructor
	 */
	public ParticipationsPersistenceJPA() {
		super(ParticipationsEntity.class);
	}

	@Override
	public ParticipationsEntity load( Integer id, String email ) {
		// Build the composite key
		ParticipationsEntityKey key = new ParticipationsEntityKey( id, email );
		return super.load( key );
	}

	@Override
	public boolean delete( Integer id, String email ) {
		// Build the composite key
		ParticipationsEntityKey key = new ParticipationsEntityKey( id, email );
		return super.delete( key );
	}

	@Override
	public boolean delete(ParticipationsEntity entity) {
		if ( entity != null ) {
			// Build the composite key
			ParticipationsEntityKey key = new ParticipationsEntityKey( entity.getId(), entity.getEmail() );
			return super.delete( key );
		}
		return false ;
	}

	@Override
	public long countAll() {
		// JPA operation definition 
		JpaOperation operation = new JpaOperation() {
			@Override
			public Object exectue(EntityManager em) throws PersistenceException {
				Query query = em.createNamedQuery("ParticipationsEntity.countAll");
				return query.getSingleResult() ;
			}
		} ;
		// JPA operation execution 
		return (Long) execute(operation);
	}

}
